"""empty message

Revision ID: 06c42387ad1a
Revises: ed3cfd3e9d0f
Create Date: 2023-10-22 15:27:34.080296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c42387ad1a'
down_revision = 'ed3cfd3e9d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
