"""Added account table

Revision ID: 721344c75209
Revises: 06c42387ad1a
Create Date: 2023-12-18 19:31:50.658413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721344c75209'
down_revision = '06c42387ad1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
